@echo off
setlocal
set "REPO_ROOT=%~dp0..\..\."
for %%I in ("%REPO_ROOT%") do set "REPO_ROOT=%%~fI"
cd /d "%REPO_ROOT%"
call sim\p4gates\implicit_gate.bat "sim\p5wu\run\xvlog_wu.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5wu\run\xelab_wu.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\fcrun\xvlog_fc.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\fcrun\xelab_fc.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\flowrun\xvlog_flow.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\flowrun\xelab_flow.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xvlog_tb.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xelab_run.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xvlog_st.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xelab_st.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xvlog_p.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xelab_p.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xvlog_w.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xvlog_w_hls.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xelab_w.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xvlog_adv.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5sim\xelab_adv.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5d_multi\main\xvlog_multi.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5d_multi\main\xelab_multi.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5wu_regress\wraphead\xvlog_w.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5wu_regress\wraphead\xelab_w.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5wu_regress\wraphead\xvlog_w_hls.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5wu_regress\wrapnew\xvlog_w.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5wu_regress\wrapnew\xelab_w.log" "[static]"
call sim\p4gates\implicit_gate.bat "sim\p5wu_regress\wrapnew\xvlog_w_hls.log" "[static]"
for /r "%REPO_ROOT%\sim\p4gates\work_20261007_014439" %%F in (*.log) do call sim\p4gates\implicit_gate.bat "%%F" "[matrix]"
exit /b 0
