#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_pinmap.py -- 从 .ltx 抽出 VIO 的**引脚位映射**, 生成 probe_lat.tcl 用的 pinmap.tcl

  为什么需要它 (2026-09-30 实测):
    Vivado 综合会把宽探针网按**常量位**切碎 —— `lat_piN` 那根 128 位别名网被拆成
    若干片, 常量位甚至完全不出现在 .ltx 的探针表里。实测 (第 1 次板级尝试):
        probe_in0 = {[0:31] ro_fe_a}{[32:63] ro_fe_b}{[64:95] dp_vs_r...}{[96:127] dp_c_r}
        probe_in2 = {[0:114] lat_pi2_1}{[115] lat_clr}{[116] fe_rst_n}{[117:119] lat_pi2}
                    {[120:127] <const0>_1..8}
        probe_in4 = {[0:31] lat_pi4_1}{[32:33] drp_req_go_1}{[34:35] lat_pi4_2}
                    {[36:63] <const0>_21..47}{[64:127] lat_pi4}
    ⇒ 直接读 "128 位探针" 拿到的是一堆**碎片**, 位序还会错。
    好在这张表**完整保存在 .ltx 里** (每个引脚的 name/direction/leftIndex/rightIndex
    + nets[0].name) ⇒ 无需重建位流, 只要按表把碎片拼回 128 位即可。

  输出: pinmap.tcl
    set PINMAP {{<vio_port> <left> <right> <hw_probe_name>} ...}
    其中 <hw_probe_name> = "" 表示常量位 (值为 0, 不必读)。
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
LAT  = os.path.dirname(HERE)
LTX  = os.path.join(LAT, os.pardir, os.pardir, "vivado_prj", "p7b_lat_prj.runs",
                    "impl_1", "wrapper_p4.ltx")
OUT  = os.path.join(HERE, "pinmap.tcl")

def main():
    ltx = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else LTX)
    out = os.path.abspath(sys.argv[2] if len(sys.argv) > 2 else OUT)
    d = json.load(open(ltx, encoding="utf-8"))
    rows = []
    nvio = 0
    for c in d["ltx_root"]["ltx_data"][0]["debug_cores"]:
        if c.get("type") != "VIO_V2":
            continue
        nvio += 1
        for pin in c["pins"]:
            nets = pin.get("nets", [])
            nm = nets[0]["name"] if nets else ""
            if nm.startswith("u_lat/<const") or "<const" in nm:
                nm = ""                       # 常量位: 值恒 0
            rows.append((pin["name"], int(pin["leftIndex"]), int(pin["rightIndex"]), nm))
    if nvio != 1:
        print("WARN: %d VIO cores found (expected 1)" % nvio)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("# AUTO-GENERATED by gen_pinmap.py from %s -- DO NOT EDIT\n"
                % os.path.basename(ltx))
        f.write("# {<vio port> <left> <right> <hw probe name or \"\">}\n")
        f.write("set PINMAP {\n")
        for r in rows:
            f.write("  {%s %d %d {%s}}\n" % (r[0], r[1], r[2], r[3]))
        f.write("}\n")
    print("WROTE %s  entries=%d" % (out, len(rows)))
    # 一句人读的核对: 每个输入探针的位覆盖是否连续完整
    from collections import defaultdict
    cov = defaultdict(list)
    for (p, l, r, nm) in rows:
        cov[p].append((l, r, nm))
    for p in sorted(cov):
        iv = sorted(cov[p])
        tot = sum(r - l + 1 for (l, r, _) in iv)
        gaps = []
        pos = 0
        for (l, r, _) in iv:
            if l != pos:
                gaps.append((pos, l - 1))
            pos = r + 1
        print("  %-11s pieces=%2d bits=%3d gaps=%s" % (p, len(iv), tot, gaps if gaps else "none"))

if __name__ == "__main__":
    main()
