# auto-generated by probe.tcl for tag=sstl12
set_property -dict {PACKAGE_PIN T25 IOSTANDARD DIFF_SSTL12} [get_ports clk_p]
set_property -dict {PACKAGE_PIN U25 IOSTANDARD DIFF_SSTL12} [get_ports clk_n]
set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVCMOS33} [get_ports led_locked]
create_clock -period 10.000 -name sys_clk [get_ports clk_p]
