#=====================================================================
# probe.tcl -- P6b 引脚 / MMCM 合法性探针 (非工程模式, 参数经环境变量传入)
#
# 每个变体都真跑 synth -> opt -> place (FLOW=full 时再 route),
# 拿 DRC / 时钟报告 / 时序做证据。全部 read-only, 不烧板。
#
# 环境变量:
#   PROBE_TAG    变体名 (决定输出文件后缀)
#   PROBE_IOSTD  clk_p/clk_n 的 IOSTANDARD
#   PROBE_MULT   CLKFBOUT_MULT_F
#   PROBE_OUTDIV CLKOUT0_DIVIDE_F
#   PROBE_DIVD   DIVCLK_DIVIDE
#   PROBE_PIN_P  clk_p 引脚 (T25 或 NOTGC -> 自动选一个 bank65 非 GC 脚)
#   PROBE_PIN_N  clk_n 引脚 (U25 或 NOTGC)
#   PROBE_FLOW   place | full
#=====================================================================
set part_name xcku5p-ffvb676-1-e

set tag    $::env(PROBE_TAG)
set iostd  $::env(PROBE_IOSTD)
set mult   $::env(PROBE_MULT)
set outdiv $::env(PROBE_OUTDIV)
set divd   $::env(PROBE_DIVD)
set pinp   $::env(PROBE_PIN_P)
set pinn   $::env(PROBE_PIN_N)
set flow   $::env(PROBE_FLOW)
set inper  $::env(PROBE_INPER)

set root D:/repo/XCKU5PMini/udp_hls_10g/board/ku5p_probe/clkgen_p6b
set rtl  D:/repo/XCKU5PMini/udp_hls_10g/rtl

# 非 GC 负对照: bank 65 里一对确定不是 GC 的差分脚
if {$pinp eq "NOTGC"} { set pinp "N24" }
if {$pinn eq "NOTGC"} { set pinn "P24" }

set xdc "$root/pins_$tag.xdc"
set fp [open $xdc w]
puts $fp "# auto-generated by probe.tcl for tag=$tag"
puts $fp "set_property -dict {PACKAGE_PIN $pinp IOSTANDARD $iostd} \[get_ports clk_p\]"
puts $fp "set_property -dict {PACKAGE_PIN $pinn IOSTANDARD $iostd} \[get_ports clk_n\]"
puts $fp "set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVCMOS33} \[get_ports led_locked\]"
puts $fp "create_clock -period $inper -name sys_clk \[get_ports clk_p\]"
close $fp

# 顶层也按参数生成 (MMCM 的 CLKIN1_PERIOD 必须与 create_clock 一致, 否则 Vivado 报错;
# 换个参考频率 (如 125 MHz i_rxc 退路) 只改 PROBE_INPER 即可)
set topv "$root/probe_top_$tag.v"
set fp [open $topv w]
puts $fp "// auto-generated by probe.tcl for tag=$tag (inper=$inper mult=$mult divd=$divd outdiv=$outdiv)"
puts $fp "module probe_design ("
puts $fp "    input  wire clk_p,"
puts $fp "    input  wire clk_n,"
puts $fp "    output wire led_locked"
puts $fp ");"
puts $fp "    wire clk_dp, clk_ref, locked, rst_dp;"
puts $fp "    clk_gen_p6b #("
puts $fp "        .SIM_BYPASS       (0),"
puts $fp "        .CLKIN1_PERIOD_NS ($inper),"
puts $fp "        .CLKFBOUT_MULT_F  ($mult),"
puts $fp "        .DIVCLK_DIVIDE    ($divd),"
puts $fp "        .CLKOUT0_DIVIDE_F ($outdiv)"
puts $fp "    ) u_clkgen ("
puts $fp "        .clk_p(clk_p), .clk_n(clk_n), .rst_ext(1'b0),"
puts $fp "        .clk_dp(clk_dp), .clk_in_100(clk_ref), .locked(locked), .rst_dp(rst_dp));"
puts $fp "    reg \[24:0\] cnt;"
puts $fp "    always @(posedge clk_dp) if (rst_dp) cnt <= 25'd0; else cnt <= cnt + 25'd1;"
puts $fp "    assign led_locked = locked ^ cnt\[24\] ^ clk_ref;"
puts $fp "endmodule"
close $fp

puts "########## PROBE $tag START (iostd=$iostd inper=$inper mult=$mult outdiv=$outdiv divd=$divd pins=$pinp/$pinn flow=$flow) ##########"

read_verilog $topv
read_verilog "$rtl/clk_gen_p6b.v"
read_xdc $xdc

if {[catch { synth_design -top probe_design -part $part_name } err]} {
    puts "PROBE_RESULT $tag SYNTH_ABORT"
    puts "PROBE_ERR $err"
    exit 0
}
puts "PROBE_STEP $tag synth OK"

if {[catch { opt_design } err]} {
    puts "PROBE_RESULT $tag OPT_ABORT"; puts "PROBE_ERR $err"; exit 0
}
puts "PROBE_STEP $tag opt OK"

if {[catch { place_design } err]} {
    puts "PROBE_RESULT $tag PLACE_ABORT"; puts "PROBE_ERR $err"
    catch { report_drc -file "$root/probe_${tag}_drc.rpt" }
    exit 0
}
puts "PROBE_STEP $tag place OK"
report_drc -file "$root/probe_${tag}_drc.rpt"
report_utilization -file "$root/probe_${tag}_util.rpt"
report_clocks -file "$root/probe_${tag}_clocks.rpt"

if {$flow eq "full"} {
    if {[catch { route_design } err]} {
        puts "PROBE_RESULT $tag ROUTE_ABORT"; puts "PROBE_ERR $err"; exit 0
    }
    puts "PROBE_STEP $tag route OK"
    report_timing_summary -file "$root/probe_${tag}_timing.rpt"
    report_clock_networks -file "$root/probe_${tag}_clknet.rpt"
    report_drc -file "$root/probe_${tag}_drc.rpt"
}

# ---- 关键读数摘要 (直接打屏, 便于入库) ----
puts "---------- $tag: DRC ----------"
set drc_file "$root/probe_${tag}_drc.rpt"
if {[file exists $drc_file]} {
    set fh [open $drc_file r]
    set nviol 0
    while {[gets $fh line] >= 0} {
        if {[string match "*Violations found*" $line] || [string match "*Rule*Severity*" $line]} {
            puts "  DRC| $line"
        }
    }
    close $fh
}
puts "---------- $tag: CLOCKS ----------"
catch { set clkstr [report_clocks -return_string] ; puts $clkstr }
puts "---------- $tag: MMCM placement ----------"
catch { puts [get_cells -hier -filter {REF_NAME =~ "MMCME4*"}] }
catch { puts "MMCM site: [get_property LOC [get_cells -hier -filter {REF_NAME =~ \"MMCME4*\"}]]" }
catch { puts "IBUFDS    : [get_cells -hier -filter {REF_NAME =~ \"IBUFDS*\"}]" }
puts "########## PROBE $tag DONE ##########"
