// auto-generated by probe.tcl for tag=alt125_m10d1o8 (inper=8.000 mult=10.000 divd=1 outdiv=8.000)
module probe_design (
    input  wire clk_p,
    input  wire clk_n,
    output wire led_locked
);
    wire clk_dp, clk_ref, locked, rst_dp;
    clk_gen_p6b #(
        .SIM_BYPASS       (0),
        .CLKIN1_PERIOD_NS (8.000),
        .CLKFBOUT_MULT_F  (10.000),
        .DIVCLK_DIVIDE    (1),
        .CLKOUT0_DIVIDE_F (8.000)
    ) u_clkgen (
        .clk_p(clk_p), .clk_n(clk_n), .rst_ext(1'b0),
        .clk_dp(clk_dp), .clk_in_100(clk_ref), .locked(locked), .rst_dp(rst_dp));
    reg [24:0] cnt;
    always @(posedge clk_dp) if (rst_dp) cnt <= 25'd0; else cnt <= cnt + 25'd1;
    assign led_locked = locked ^ cnt[24] ^ clk_ref;
endmodule
