#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
gen_mutants.py -- generate the two mutants used by run_mut5.bat, from the FROZEN
sources (rtl/snap_cdc.v, tb/tb_snap_cdc.v), one single change each.

Why a generator instead of a hand-copied file (same idea as sim/fifoasync/mut/gen_mutants.py):
  * a hand copy can silently drift from the frozen RTL/TB, and then the mutation
    check proves nothing about the artifact that actually ships;
  * every mutation asserts "exactly 1 replacement" -- if the source changes so
    that the pattern is gone (or appears twice), this script FAILS LOUDLY
    instead of writing a mutant that is not the mutation it claims to be.
  * byte-level read/write: the .v files are UTF-8 with Chinese comments and LF
    endings; decoding/re-encoding them could change bytes we did not intend.

Mutants:
  A) snap_cdc_mut_nolatch.v  (DUT)  dout_a <= hold_b  ->  dout_a <= din_b
       = "the latch that snap_cdc exists for is removed".  Must be CAUGHT at every NW.
  B) tb_snap_cdc_nwbug.v     (TB)   the `TB_NW_36 branch is deleted
       = a faithful reproduction of the ORIGINAL defect: the runner asks for 36,
       the TB silently falls back to 32.  Must be CAUGHT in the NW=36 run ONLY
       (the other four widths must still PASS -- that is what proves the new
       width assertion is per-run, i.e. it does not just fail everything).
  C) run_gate_selfneg.bat    (BAT)  the real gate bat, DUT path swapped to mutant A
       = the gate script's own negative control; MUST exit 1.  Guards the
       "vacuous gate" failure mode: exit 0 on a healthy DUT proves nothing about
       the FAIL path.
       = a faithful reproduction of the ORIGINAL defect: the runner asks for 36,
       the TB silently falls back to 32.  Must be CAUGHT in the NW=36 run ONLY
       (the other four widths must still PASS -- that is what proves the new
       width assertion is per-run, i.e. it does not just fail everything).

Usage:  python gen_mutants.py     (writes the two files next to this script)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
RTL = os.path.join(ROOT, "rtl", "snap_cdc.v")
TB = os.path.join(ROOT, "tb", "tb_snap_cdc.v")

OUT_DUT = os.path.join(HERE, "snap_cdc_mut_nolatch.v")
OUT_TB = os.path.join(HERE, "tb_snap_cdc_nwbug.v")

# C) run_gate_selfneg.bat -- the REAL gate bat with only the DUT path swapped to the
#    no-latch mutant, i.e. the gate's own negative control: it must exit 1.
#    Rationale: the project has spent a day killing "gates that can never fail"
#    (vacuous gates).  Exit 0 on a healthy DUT is NOT evidence that the FAIL path
#    works.  This variant proves the FAIL path end-to-end (5 x FAIL => BAD=1 => 1).
GATE_BAT = os.path.join(os.path.dirname(HERE), "run_tb_snap_cdc.bat")
OUT_SELFNEG = os.path.join(HERE, "run_gate_selfneg.bat")


def sub_once(data, old, new, what):
    n = data.count(old)
    if n != 1:
        sys.stderr.write(
            "GEN-MUTANT-FAIL: %s: expected exactly 1 occurrence, found %d\n"
            "  (the frozen source changed -> regenerate/inspect before trusting "
            "this mutation)\n" % (what, n))
        sys.exit(1)
    return data.replace(old, new)


def main():
    with open(RTL, "rb") as f:
        rtl = f.read()
    mut_a = sub_once(rtl, b"dout_a <= hold_b;",
                     b"dout_a <= din_b;   // MUTANT-NOLATCH (generated, do not edit)",
                     "rtl/snap_cdc.v: dout_a <= hold_b")
    with open(OUT_DUT, "wb") as f:
        f.write(mut_a)

    with open(TB, "rb") as f:
        tb = f.read()
    branch = (b"`elsif TB_NW_36\n"
              b"    `define TB_NW 36\n"
              b"    `define TB_NW_SRC \"TB_NW_36\"\n"
              b"    `define TB_NW_GIVEN\n")
    mut_b = sub_once(tb, branch, b"",
                     "tb/tb_snap_cdc.v: `elsif TB_NW_36 branch")
    with open(OUT_TB, "wb") as f:
        f.write(mut_b)

    with open(GATE_BAT, "rb") as f:
        gate = f.read()
    banner = (b"REM === GENERATED by mut5_nw/gen_mutants.py -- DO NOT EDIT, REGENERATE ===\r\n"
              b"REM run_gate_selfneg.bat = sim/snapcdc/run_tb_snap_cdc.bat with ONE change:\r\n"
              b"REM   the DUT compiled for every width is mut5_nw/snap_cdc_mut_nolatch.v.\r\n"
              b"REM It is the gate script's OWN negative control: with the latch removed the\r\n"
              b"REM criteria must fire at every width, so this script MUST print\r\n"
              b"REM   SNAP_CDC_GATE_ALL: FAIL   and exit 1.\r\n"
              b"REM (exit 0 on a healthy DUT does not prove the FAIL path exists.)\r\n")
    gate2 = sub_once(gate, b"@echo off\r\n", b"@echo off\r\n" + banner,
                     "run_tb_snap_cdc.bat: @echo off")
    gate2 = sub_once(gate2, b"-d TB_NW_%W% %ROOT%\\rtl\\snap_cdc.v",
                     b"-d TB_NW_%W% %~dp0snap_cdc_mut_nolatch.v",
                     "run_tb_snap_cdc.bat: xvlog DUT path")
    # keep its evidence files apart from the real gate's (same dir -> same names)
    for old, new, n in ((b"fingerprint", b"fingerprint_selfneg", 5),
                        (b"gate_nw%W%.txt", b"gate_selfneg_nw%W%.txt", 2)):
        c = gate2.count(old)
        if c != n:
            sys.stderr.write("GEN-MUTANT-FAIL: selfneg rename %r: found %d, expected %d\n"
                             % (old, c, n))
            sys.exit(1)
        gate2 = gate2.replace(old, new)
    with open(OUT_SELFNEG, "wb") as f:
        f.write(gate2)

    print("wrote %s (%d bytes, %+d)" % (OUT_DUT, len(mut_a), len(mut_a) - len(rtl)))
    print("wrote %s (%d bytes, %+d)" % (OUT_TB, len(mut_b), len(mut_b) - len(tb)))
    print("wrote %s (%d bytes, %+d)" % (OUT_SELFNEG, len(gate2), len(gate2) - len(gate)))
    print("GEN-MUTANTS: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
