@echo off
REM ===========================================================================
REM run_gate_teeth.bat -- P7B-RETXFIX r5: negative controls (teeth check) for
REM   the two new txframe compile arms (t3/t4) of sim\p5wu_p1p2\run_xvlog_wrapper63.bat
REM
REM   5 sub-runs, expected rc matrix (nonzero = xvlog ERROR):
REM     clean_t4 : unmutated copy, board defs  -> rc 0   (control: arm not always-fail)
REM     movl_t3  : syntax error injected after `ifdef TCP_TX_OVL, macro OFF
REM                                             -> rc 0   (error sits in skipped region)
REM     movl_t4  : same file, macro ON          -> rc != 0 (arm has teeth + macro-sensitive)
REM     mdp_t3   : syntax error injected after DP_156MHZ RTO_LIM line, macro ON
REM                                             -> rc != 0
REM     mdp_t4   : same file, board defs        -> rc != 0
REM
REM   Mutants are generated by mkneg_txframe.py (missing anchor => exit 2,
REM   so an "empty mutant" can never pass silently).
REM   NOTE: all comments in this .bat are ASCII on purpose (project rule) --
REM   non-ASCII REM text plus a ">" character once got the line redirected and
REM   cmd then tried to execute a fragment of the comment. Do not "fix" this.
REM ===========================================================================
setlocal
set XV=C:\AMDDesignTools\2025.2\Vivado\bin
set PY=C:\Users\zhxue\anaconda3\python.exe
cd /d %~dp0
"%PY%" mkneg_txframe.py
if errorlevel 1 exit /b 2
cd negctl
set D3=-d APP_MODE -d P7B_10G -d PCIE_OBS -d DEV_USP -d DP_156MHZ -d UDP_TX_OVL
set NBAD=0
call :chk "clean_t4"  "%D3% -d TCP_TX_OVL" clean.v   0
call :chk "movl_t3"   "%D3%"                mut_ovl.v 0
call :chk "movl_t4"   "%D3% -d TCP_TX_OVL"  mut_ovl.v 1
call :chk "mdp_t3"    "%D3%"                mut_dp.v  1
call :chk "mdp_t4"    "%D3% -d TCP_TX_OVL"  mut_dp.v  1
echo.
if %NBAD% NEQ 0 ( echo TEETH_FAIL %NBAD% ) else ( echo TEETH_PASS 5/5 )
if %NBAD% NEQ 0 exit /b 1
exit /b 0

:chk
set TAG=%~1
set DEFS=%~2
set SRC=%~3
set EXP=%~4
call "%XV%\xvlog.bat" -work xil_defaultlib %DEFS% "%SRC%" > "xvlog_teeth_%TAG%.log" 2>&1
set RC=%ERRORLEVEL%
REM NOTE: no "if (...) else (...)" one-liners here on purpose -- an unescaped ")"
REM in echo text closes the enclosing block early (both branches then run).
if "%EXP%"=="0" goto :exp_zero
if "%RC%"=="0" goto :bad_nz
echo [OK  ] %TAG% rc=%RC% expected nonzero
exit /b 0
:exp_zero
if not "%RC%"=="0" goto :bad_zero
echo [OK  ] %TAG% rc=0 expected 0
exit /b 0
:bad_zero
echo [FAIL] %TAG% rc=%RC% expected 0
set /a NBAD+=1
exit /b 0
:bad_nz
echo [FAIL] %TAG% rc=0 expected nonzero
set /a NBAD+=1
exit /b 0
